### ISSUE TITLE
Trill square not completely flat

### ISSUE THREAD

**Issue by wjslager** [BelaPlatform/Trill#4] opened 2021-07-27 13:28 UTC
I have a trill square here that is not 100% flat. Not really a big issue but if one would want to mount it flush in a surface the edges could stand out.

https://user-images.githubusercontent.com/3001621/127160647-299aba64-3ae9-411e-b594-94e6d92a7a33.mp4

I think this can be fixed by having equal amounts of copper on each layer, it seems like the backside of the PCB has only traces and no plane.

**Comment by apmcpherson** [comment] 2021-07-28 17:32
This is a good point, but maybe not an easy fix: adding solid copper to the back could increase baseline capacitance of the sensors and ultimately lower the sensitivity of the readings. We will keep an eye on the assembly process to see what we can do to keep them as flat as possible. Since the boards are relatively thin and partly flexible, they could perhaps be secured to a rigid backplane using adhesive.

**Comment by mxa** [comment] 2023-10-24 09:53
Closing, since this is a  issue inherent of the properties of the PCB, (thin, large, 4-layer), can't be solved by designing it differently while keeping the same properties.

**Comment by mxa** [comment] 2023-10-24 09:53
Closing, since this is a  issue inherent of the properties of the PCB, (thin, large, 4-layer), can't be solved by designing it differently while keeping the same properties.

**Comment by mxa** [comment] 2023-10-24 09:54
Closing, since this is a  issue inherent of the properties of the PCB, (thin, large, 4-layer), can't be solved by designing it differently while keeping the same properties.

**Comment by mxa** [comment] 2023-10-24 09:54
Closing, since this is a  issue inherent of the properties of the PCB, (thin, large, 4-layer), can't be solved by designing it differently while keeping the same properties.

**Comment by mxa** [comment] 2023-10-24 09:54
Closing, since this is a  issue inherent of the properties of the PCB, (thin, large, 4-layer), can't be solved by designing it differently while keeping the same properties.

**Closed as completed by mxa** 2023-10-24 09:54 UTC
